---
title: "Mini-Project 2"
author: "Yvonne Niyonzima, Duanyue Yun, Junzhou Liu"
date: "March 24, 2017"
output: html_document
---


## Loading the data

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidyr)

```


```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}

#we first join the  data by the "candidate id"
joined <- candidates %>%
  full_join(contributions, by = "cand_id")
##We chose only candidates who are seeking theie state senate seats in the years between 2010 and 2016 using the verb "filter". We also use selc to have only the variables that we need. 
Sjoined <- joined %>%
  filter(cand_election_yr >= 2010 & cand_office == "S") %>%
  select(cand_id, cand_party_affiliation, cand_election_yr, cand_ici, cand_state)
  
Scandidates <-  candidates %>%
  filter(cand_election_yr >= 2010 & cand_office == "S") %>%
  select(cand_id, cand_party_affiliation, cand_election_yr, cand_ici, cand_state)


```

